### ISSUE TITLE
No Graphing

### ISSUE THREAD

**Issue by RyanGuyCode** [kjake/internet-speedtest-docker#1]
updating my issue.
The docker launches, and runs, but does not run the speedtest. I get 0 upload 0 download.

here is what I am running:
`version: '2'
services:
  db:
    image: influxdb 
    container_name: influxdb
    networks:
      - default
    volumes:
      - /srv/dev-disk-by-label-East500/Config/SpeedTest/:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_DB=speedtest
  web:
    image: kjake/internet-speedtest-docker:grafana
    container_name: speedweb
    ports:
      - "3000:3000"
    networks:
      - default
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=teste
  testing:
    image: kjake/internet-speedtest-docker:speedtest
    container_name: speedtest
    networks:
      - default
    environment:
      - TEST_INTERVAL=30

networks:
  default:
    driver: bridge`

LOGS:
`
Date: Sat, 28 Mar 2020 15:09:01 GMT
,
X-Request-Id: 0e669778-7106-11ea-8002-0242ac190002
,
X-Influxdb-Version: 1.7.10
,
X-Influxdb-Build: OSS
,
Request-Id: 0e669778-7106-11ea-8002-0242ac190002
,
Content-Type: application/json
,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    28    0     0  100    28      0   1647 --:--:-- --:--:-- --:--:--  1647,
HTTP/1.1 204 No Content
,
                                 Dload  Upload   Total   Spent    Left  Speed,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
X-Request-Id: 0e5bbe89-7106-11ea-8001-0242ac190002
,
Request-Id: 0e5bbe89-7106-11ea-8001-0242ac190002
,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    30    0     0  100    30      0    491 --:--:-- --:--:-- --:--:--   491`

docker version: 5:19.03.8~3-0~debian-buster
running in OpenMediaVault

![image](https://user-images.githubusercontent.com/23059787/77826293-8255d280-70dc-11ea-9250-b9675514f12d.png)

**Comment by kjake** [comment]
Whoa. I didn't get notification of this!!

I have seen this when the container isn't allowed to connect to the required speedtest server(s):port(s).

According to some [Ookla docs](https://support.ookla.com/hc/en-us/articles/234578628-Speedtest-Server-Requirements), you may need to allow outbound firewall traffic from the container via tcp/udp 5060 and 8080 in addition to normal 80/443 traffic.

**Comment by RyanGuyCode** [comment]
It’s really strange because in my Firewall it was fine and then just suddenly stopped working. And that was without any firewall changes.

Regards,
Ryan Milton
On Apr 7, 2020, 2:51 PM -0500, kjake <notifications@github.com>, wrote:

Whoa. I didn't get notification of this!!

I have seen this when the container isn't allowed to connect to the required speedtest server(s):port(s).

According to some Ookla docs<https://support.ookla.com/hc/en-us/articles/234578628-Speedtest-Server-Requirements>, you may need to allow outbound firewall traffic from the container via tcp/udp 5060 and 8080 in addition to normal 80/443 traffic.

**Comment by kjake** [comment]
Could try to debug this, to some degree, with trying to run it manually.

1. From the Docker Host (SSH/Console), run `docker exec -it speedtest /bin/sh`
1. Should see a prompt like `/ $`
1. Run `/app/speedtest/speedtest.py`

Should see output like so:
```
Retrieving speedtest.net configuration...
Testing from ISP (xxx.xxx.xxx.xxx)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by ISP (Location) [Dist km]: Ping ms
Testing download speed................................................................................
Download: 231.10 Mbit/s
Testing upload speed......................................................................................................
Upload: 14.36 Mbit/s
```

**Comment by RyanGuyCode** [comment]
So, just for clarification: when you say allow outbound firewall traffic from the container, you mean my primary firewall? or do you mean on the server running docker? Because my firewall definitely allows this.

> Whoa. I didn't get notification of this!!
> 
> I have seen this when the container isn't allowed to connect to the required speedtest server(s):port(s).
> 
> According to some [Ookla docs](https://support.ookla.com/hc/en-us/articles/234578628-Speedtest-Server-Requirements), you may need to allow outbound firewall traffic from the container via tcp/udp 5060 and 8080 in addition to normal 80/443 traffic.

**Comment by RyanGuyCode** [comment]
> 3\. /app/speedtest/speedtest.py

it took forever...finally:
Config# docker exec -it speedtest /bin/sh
/ $ /app/speedtest/speedtest.py
Retrieving speedtest.net configuration...
Testing from Suddenlink Communications (47.222.229.142)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Education Service Center, Region 13 (Austin, TX) [24.09 km]: 1800000.0 ms
Testing download speed................................................................................
Download: 0.00 Mbit/s
Testing upload speed......................................................................................................
Upload: 0.00 Mbit/s

**Comment by RyanGuyCode** [comment]
@kjake debugged..I found a renegade rule that blocked outbound 8080 from this server. All good
