### ISSUE TITLE
How do i get this running?

### ISSUE THREAD

**Issue by BloodyMikey** [kjake/internet-speedtest-docker#2]
How do i get this running if i allready have grafana?

**Comment by kjake** [comment]
If you look at the shell script that is run in the speedtest container, it needs to be able to push results into a 'db' host, which in this project's case, is a DNS entry setup by Docker Compose for InfluxDb
https://github.com/kjake/internet-speedtest-docker/blob/speedtest/scripts/init_test_connection.sh
https://github.com/kjake/internet-speedtest-docker/blob/master/docker-compose.yml

So, if you took the stock Docker Compose file, but removed the 'web' service, you should get the speed testing container and influx container with results making it into the Db.  Then you'll have to plumb Graphana to the InfluxDb and add the info to a Dashboard of your own.

For the Dashboard, you might be able to import what I'm setting as the default:
https://github.com/kjake/internet-speedtest-docker/blob/grafana/conf/home.json
